language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.3.7

install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -q coverage
  - pip install -q pep8
  - python setup.py -q install

script: python setup.py test
