language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO_VERSION=1.4.2
  - DJANGO_VERSION=1.4.1
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.3

install:
  - pip install -q django==$DJANGO_VERSION
  - pip install -q coverage
  - pip install -q pep8==1.3.1
  - python setup.py -q install

script: python setup.py test